#!/bin/bash 

# CHANGE YOUR VARIABLES HERE!

WIRELESS_DEVICE=wlan0
GROUP_NUMBER=9
COMPUTER_NUMBER=1
MULTICAST_SUBNET=228.0.0.0/8

# DO NOT CHANGE BELOW THIS LINE!



# Make sure only root can run our script
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   echo "Example: sudo ./adhoc_setup" 1>&2
   exit 1
fi


echo "/**************************\\"
echo " *   adhoc_setup script   * "
echo " *     Kevin Alberts      * "
echo "\**************************/"
echo ""
echo "Current settings: (edit the script with 'nano adhoc_setup' to change)"
echo "Wireless device:  "$WIRELESS_DEVICE
echo "Group number:     "$GROUP_NUMBER
echo "Computer number:  "$COMPUTER_NUMBER
echo "Multicast subnet: "$MULTICAST_SUBNET
echo ""

if [ -e /usr/bin/systemctl ] || [ -e /bin/systemctl ]; then
	if [ -e /usr/bin/NetworkManager ] || [ -e /usr/sbin/NetworkManager ]; then
		echo -ne "Stopping NetworkManager..."
		systemctl stop network-manager &> /dev/null
		systemctl stop NetworkManager &> /dev/null
	else
		echo -ne "Stopping netctl..."
		systemctl stop netctl &> /dev/null
	fi
else
	if [ -e /usr/bin/NetworkManager ] || [ -e /usr/sbin/NetworkManager ]; then
		echo -ne "Stopping NetworkManager..."
		service network-manager stop &> /dev/null
		service NetworkManager stop &> /dev/null
	else
		echo -ne "Stopping netctl..."
		service netctl stop &> /dev/null
	fi
fi
sleep 1
tput cuf $(($(tput cols)-36))
echo -ne "["
tput setaf 2
echo -ne "OK"
tput sgr0
echo "]     "
echo -ne "Taking down wireless interface..."
ifconfig $WIRELESS_DEVICE down
tput cuf $(($(tput cols)-42))
echo -ne "["
tput setaf 2
echo -ne "OK"
tput sgr0
echo -ne "]     "
echo -ne "Configuring ad-hoc network..."
iwconfig $WIRELESS_DEVICE mode ad-hoc
iwconfig $WIRELESS_DEVICE channel $((($GROUP_NUMBER % 11)+1))
if [ $GROUP_NUMBER -gt 9 ]; then
	iwconfig $WIRELESS_DEVICE ap f8:d1:11:64:5e:$GROUP_NUMBER
else
	iwconfig $WIRELESS_DEVICE ap f8:d1:11:64:5e:a$GROUP_NUMBER
fi
iwconfig $WIRELESS_DEVICE essid groep$GROUP_NUMBER
iwconfig $WIRELESS_DEVICE key 1234567890
tput cuf $(($(tput cols)-38))
echo -ne "["
tput setaf 2
echo -ne "OK"
tput sgr0
echo "]     "
echo -ne "Starting wireless network interface..."
ifconfig $WIRELESS_DEVICE 192.168.5.$COMPUTER_NUMBER up
tput cuf $(($(tput cols)-47))
echo -ne "["
tput setaf 2
echo -ne "OK"
tput sgr0
echo "]     "
echo -ne "Setting up correct routing paths..."
route add -net $MULTICAST_SUBNET dev $WIRELESS_DEVICE
tput cuf $(($(tput cols)-44))
echo -ne "["
tput setaf 2
echo -ne "OK"
tput sgr0
echo "]     "
echo "Done. If you did not see any errors above, you should be"
echo "connected to the ad-hoc network with IP address 192.168.5."$COMPUTER_NUMBER
